# Generated by Django 4.2.10 on 2024-05-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
    ]
