# Generated by Django 4.2.10 on 2024-05-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='store.attribute'),
        ),
    ]
