# Generated by Django 4.2.10 on 2024-05-08 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_item_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attributes',
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variation'),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
