# Generated by Django 4.2.10 on 2024-05-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_item_attributes_alter_itemvariation_variation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attribute_child', models.ManyToManyField(blank=True, to='store.attributechild')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='store.attribute'),
        ),
    ]
