# Generated by Django 4.2.10 on 2024-05-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_attributechild_attribute_item_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
