# Generated by Django 4.2.10 on 2024-05-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_attribute_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='price',
        ),
        migrations.AddField(
            model_name='attributechild',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
