# Generated by Django 4.2.10 on 2024-05-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_attribute_price_attributechild_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributechild',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
