# Generated by Django 4.2.10 on 2024-05-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_subcategory_category_category_sub_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributechild',
            name='price',
        ),
    ]
