# Generated by Django 4.2.10 on 2024-05-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_variations',
            field=models.ManyToManyField(blank=True, to='store.itemvariation'),
        ),
    ]
