# Generated by Django 4.2.10 on 2024-05-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_subcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
