# Generated by Django 4.2.10 on 2024-05-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_subcategory_ischecked'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='selected_sub_categories_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
