# Generated by Django 4.2.10 on 2024-05-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_category_selected_sub_categories_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='selected_sub_categories_id',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='isChecked',
        ),
        migrations.AddField(
            model_name='item',
            name='selected_cat_sub_categories_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
