# Generated by Django 4.2.10 on 2024-05-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_itemattribute_alter_variation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattribute',
            name='value',
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attributes', models.ManyToManyField(to='store.itemattribute')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='value',
            field=models.ManyToManyField(blank=True, to='store.attributechild'),
        ),
    ]
