# Generated by Django 4.2.10 on 2024-05-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_itemattribute_value_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='store.itemattribute'),
        ),
    ]
