# Generated by Django 4.2.10 on 2024-05-14 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_itemattribute_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='itemattribute',
            unique_together={('item', 'attribute')},
        ),
    ]
