# Generated by Django 4.2.10 on 2024-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_itemattribute_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemattribute',
            name='variation_select',
            field=models.ManyToManyField(blank=True, related_name='variation', to='store.attributechild'),
        ),
    ]
