# Generated by Django 4.2.10 on 2024-05-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_itemattribute_variation_select'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='attributes',
            new_name='item_attributes',
        ),
    ]
