# Generated by Django 4.2.10 on 2024-05-15 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_rename_attributes_variation_item_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattribute',
            name='variation_select',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='item_attributes',
        ),
        migrations.AddField(
            model_name='variation',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.attribute'),
        ),
        migrations.AddField(
            model_name='variation',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.attributechild'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
