# Generated by Django 4.2.10 on 2024-05-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_remove_itemattribute_variation_select_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
