# Generated by Django 4.2.10 on 2024-05-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_remove_variation_item_item_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
