# Generated by Django 4.2.10 on 2024-05-28 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_category_slug_shop_slug_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='attributechild',
            name='atribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_childs', to='store.attribute'),
        ),
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_child',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='store.attributechild'),
        ),
    ]
