# Generated by Django 4.2.10 on 2024-05-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_aditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='adition',
            field=models.ManyToManyField(blank=True, related_name='shops', to='store.aditions'),
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='store.category'),
        ),
        migrations.AddField(
            model_name='shop',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='shops', to='store.subcategory'),
        ),
        migrations.AlterField(
            model_name='aditions',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aditions', to='store.shop'),
        ),
    ]
