# Generated by Django 4.2.10 on 2024-05-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_shop_adition_shop_category_shop_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='owner_name',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='owner_phone',
            new_name='phone',
        ),
    ]
