# Generated by Django 4.2.10 on 2024-05-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_rename_owner_name_shop_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='variations',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='child',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='price',
        ),
        migrations.AddField(
            model_name='variation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AddField(
            model_name='variation',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='type',
            field=models.CharField(blank=True, choices=[('B', 'MULTIPLE'), ('S', 'SINGLE')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='store.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='adition',
            field=models.ManyToManyField(blank=True, null=True, related_name='shops', to='store.aditions'),
        ),
        migrations.CreateModel(
            name='VariationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.attributechild')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variation')),
            ],
        ),
    ]
