# Generated by Django 4.2.10 on 2024-05-28 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_remove_item_variations_remove_variation_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='item',
            name='selected_cat_sub_categories_id',
        ),
        migrations.AddField(
            model_name='item',
            name='adition',
            field=models.ManyToManyField(blank=True, related_name='items', to='store.aditions'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subcategory'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='adition',
            field=models.ManyToManyField(blank=True, related_name='shops', to='store.aditions'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.item'),
        ),
    ]
