# Generated by Django 4.2.10 on 2024-05-28 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_remove_item_attributes_remove_item_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.shop'),
        ),
        migrations.AlterField(
            model_name='variationvalue',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.variation'),
        ),
    ]
